
Vagrant.configure(2) do |config|

  config.vm.box = "dummy"
  
  config.vm.define "small_inst" do |config_small_inst|
    config_small_inst.vm.provider :aws do |small_inst, override|
      small_inst.keypair_name =  ENV['AWS_KEYNAME']
      small_inst.ami = "ami-d05e75b8"
      small_inst.region = "us-east-1"
      small_inst.availability_zone = "us-east-1a"
      small_inst.instance_type = "t2.small"
      small_inst.access_key_id = ENV['AWS_KEY']
      small_inst.secret_access_key = ENV['AWS_SECRET']
      small_inst.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 16 }]
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = ENV['AWS_KEYPATH']
      override.vm.provision :shell, :path => "/Users/pengfeiz/Projects/CAFI_AWS/linux.sh"
    end
  end

config.vm.define "django_inst" do |config_django_inst|
  config_django_inst.vm.provider :aws do |django_inst, override|
    django_inst.keypair_name =  ENV['AWS_KEYNAME']
    django_inst.ami = "ami-d05e75b8"
    django_inst.region = "us-east-1"
    django_inst.availability_zone = "us-east-1a"
    django_inst.instance_type = "t2.medium"
    django_inst.access_key_id = ENV['AWS_KEY']
    django_inst.secret_access_key = ENV['AWS_SECRET']
    django_inst.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 32 }]
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    override.vm.provision :shell, :path => "/Users/pengfeiz/Projects/CAFI_AWS/linux.sh"
  end
end

config.vm.define "db_inst" do |config_db_inst|
  config_db_inst.vm.provider :aws do |db_inst, override|
    db_inst.keypair_name =  ENV['AWS_KEYNAME']
    db_inst.ami = "ami-d05e75b8"
    db_inst.region = "us-east-1"
    db_inst.availability_zone = "us-east-1a"
    db_inst.instance_type = "t2.medium"
    db_inst.access_key_id = ENV['AWS_KEY']
    db_inst.secret_access_key = ENV['AWS_SECRET']
    db_inst.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 32 }]
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    override.vm.provision :shell, :path => "/Users/pengfeiz/Projects/CAFI_AWS/linux.sh"
  end
end

  # config.vm.provision :shell, path: "/Users/pengfeiz/Projects/CAFI_AWS/linux.sh"
end
